### ISSUE TITLE
Maxwell stops replicating after error communicating with mysql

### ISSUE THREAD

**Issue by acampoh** [zendesk/maxwell#1468]
Hello, I'm finding this issue every 2 or 3 days in one of our environments. the error doesn't make maxwell die and it's able to reconnect, but after even reconnecting, maxwell it's stopped or going so slow so the replication lag rises fast until it misses the last binlog, having to repoint it manually. 

I'm not sure if this can be related to a network problem or some events not being processed properly. We are using maxwell 1.24.1 and mysql 5.7. Here is the stack trace of the error found on the logs.

```
05:27:51,148 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587166690000, eventType=QUERY, serverId=763311, headerLength=19, dataLength=73, nextPosition=738493262, flags=8}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
05:27:54,640 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
05:27:54,736 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21439630554 -- restarting
05:27:54,826 INFO  BinaryLogClient - Connected to 10.230.4.76:3311 at 805d3a54-5155-ee18-4258-509028341438:1-21439630554 (sid:6379, cid:6567961)

```

thanks!

**Comment by osheroff** [comment]
can you post more examples from your logs?   I'm looking at the code in question now, I'd love to see if it correlates to a specific type of binlog event, and if the crash even happens in the same place in code or if there's EOF errors all over the place.  

Also, can you determine if anything happens at all after it hits the crash?  Ie, is maxwell emitting events or is it just running but a zombie?

**Comment by acampoh** [comment]
I think i was wrong.... looking at the log and the graphs about the performance... the times doesn't match.

Here is the full log of maxwell. The error is from today UTC time

`Using kafka version: 1.0.0
09:56:05,615 INFO  ProducerConfig - ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [my_kafka-1:9092, my_kafka-2:9092, my_kafka-3:9092, my_kafka-4:9092, my_kafka-5:9092, my_kafka-6:9092]
	buffer.memory = 33554432
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	enable.idempotence = false
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

09:56:05,687 INFO  AppInfoParser - Kafka version : 1.0.0
09:56:05,687 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
09:56:05,704 INFO  Maxwell - Maxwell v1.24.1 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[805d3a54-5155-ee18-4258-509028341438:1-21439786695], lastHeartbeat=1587166878091]
09:56:05,842 INFO  MysqlSavedSchema - Restoring schema id 38620 (last modified at Position[BinlogPosition[805d3a54-5155-ee18-4258-509028341438:1-19714436233], lastHeartbeat=1584523507506])
09:56:05,997 INFO  MysqlSavedSchema - Restoring schema id 13421 (last modified at Position[BinlogPosition[805d3a54-5155-ee18-4258-509028341438:1-1455], lastHeartbeat=0])
09:56:06,654 INFO  MysqlSavedSchema - beginning to play deltas...
09:56:06,835 INFO  MysqlSavedSchema - played 4185 deltas in 181ms
09:56:06,852 INFO  BinlogConnectorReplicator - Setting initial gtid to: 805d3a54-5155-ee18-4258-509028341438:1-21439786695
09:56:06,854 INFO  MaxwellHTTPServer - Maxwell http server starting
09:56:06,856 INFO  MaxwellHTTPServer - Maxwell http server started on port 8091
09:56:06,867 INFO  log - Logging initialized @1970ms to org.eclipse.jetty.util.log.Slf4jLog
09:56:06,921 WARN  ContextHandler - o.e.j.s.ServletContextHandler@7b793582{/,null,UNAVAILABLE} contextPath ends with /
09:56:06,939 INFO  Server - jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 1.8.0_232-b09
09:56:06,953 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21439786695 (sid:6379, cid:6595337)
09:56:06,953 INFO  BinlogConnectorLifecycleListener - Binlog connected.
09:56:06,971 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@7b793582{/format,null,AVAILABLE}
09:56:06,978 INFO  AbstractConnector - Started ServerConnector@3fcb2276{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
09:56:06,978 INFO  Server - Started @2083ms
09:57:01,995 INFO  TypeUtil - JVM Runtime does not support Modules
06:59:56,569 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587340606000, eventType=TABLE_MAP, serverId=763311, headerLength=19, dataLength=87, nextPosition=588304151, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:272) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:219) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 6 more
06:59:56,574 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
06:59:56,670 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21553774792 -- restarting
06:59:56,760 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21553774792 (sid:6379, cid:6933347)
06:59:56,760 INFO  BinlogConnectorLifecycleListener - Binlog connected.
`

and here is the graphs of messages sent and the lag from the database

![image](https://user-images.githubusercontent.com/1070678/79732069-7502c100-82f3-11ea-8294-0742b85dd9d3.png)


![image](https://user-images.githubusercontent.com/1070678/79732114-85b33700-82f3-11ea-9ce4-aa8241e89ee3.png)

so in this case the time of the increasing lag and the error doesn't match. Also as a detail that not sure if can be important, we are running maxwell in a pod inside a k8s cluster, but that's similar to the other environments we have.

**Comment by osheroff** [comment]
are these graphs averages over different database servers, or is this the lag for the database cluster with the issue?  What are the graphs measuring, exactly?  

Other graphs I'd be tempted to look at:
- cpu usage on the maxwell node
- IO bottleneck possibilities in kafka
- what does the graph look like if you restart maxwell?

**Comment by acampoh** [comment]
These graphs refer to the metrics "maxwell_messages_succeeded" and "maxwell_replication_lag" respectively. both are from the same maxwell connected only to a node.

This graph is the memory one
![image](https://user-images.githubusercontent.com/1070678/79957478-e7a1a700-8481-11ea-9453-09ced927c051.png)

CPU
![image](https://user-images.githubusercontent.com/1070678/79957642-2afc1580-8482-11ea-8bc6-5d8933f06558.png)

maxwell replication lag
![image](https://user-images.githubusercontent.com/1070678/79957757-5da60e00-8482-11ea-9c17-2ce28df4c372.png)

We have the sensation that maybe the reason is that maybe maxwell reaches a point where has memory problems and starts starving and having this kind of problems. I'm preparing a docker image with JMX enabled so i can share with you also heap / GC graphs. I'll keep you posted once i have a bit more information

**Comment by osheroff** [comment]
sounds good.  definitely looks GC bound.  getting the output of `jmap -histo:live` can help to see what's chewing all the memory.

**Comment by acampoh** [comment]
Here is the top 20 of the jmap on the process once is already starving

```
# jmap -histo:live 59 | head -n23

 num     #instances         #bytes  class name
----------------------------------------------
   1:      10645716      525417384  [C
   2:       5307599      275595880  [I
   3:      10645162      255483888  java.lang.String
   4:       5305328      254655744  com.github.shyiko.mysql.binlog.event.TableMapEventData
   5:       5334946      170718272  java.util.HashMap$Node
   6:       5308936      166129904  [B
   7:       5305622      127334928  java.lang.Long
   8:       5305371      127330488  [J
   9:       5305341      127328184  java.util.BitSet
  10:          5429       34517144  [Ljava.util.HashMap$Node;
  11:         22444        1309864  [Ljava.lang.Object;
  12:          5448         616392  java.lang.Class
  13:         19093         610976  com.zendesk.maxwell.schema.columndef.IntColumnDef
  14:         18265         438360  java.util.ArrayList
  15:          9868         315776  java.util.concurrent.ConcurrentHashMap$Node
  16:         11713         281112  com.zendesk.maxwell.schema.columndef.StringColumnDef
  17:          5586         223440  com.zendesk.maxwell.schema.Table
  18:          4366         209568  java.util.HashMap
  19:          5140         164480  com.codahale.metrics.WeightedSnapshot$WeightedSample
  20:          3554         142160  java.util.LinkedHashMap$Entry
```

also i have seen again that those exceptions are appearing again once it started having memory problems, not before. Maybe the event TableMap cannot grow more and starts throwing those exceptions when the memory is full. Here are more traces from this night.

```
22:16:59,824 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587560788000, eventType=EXT_UPDATE_ROWS, serverId=783311, headerLength=19, dataLength=8871, nextPosition=622213181, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
22:16:59,830 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
22:16:59,926 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21687084174 -- restarting
22:17:03,067 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21687084174 (sid:6379, cid:7133048)
22:17:03,067 INFO  BinlogConnectorLifecycleListener - Binlog connected.
01:47:41,314 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587561034000, eventType=EXT_UPDATE_ROWS, serverId=813311, headerLength=19, dataLength=2065, nextPosition=848654774, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
01:47:41,315 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
01:47:41,414 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21687366107 -- restarting
01:47:41,505 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21687366107 (sid:6379, cid:7133694)
01:47:41,505 INFO  BinlogConnectorLifecycleListener - Binlog connected.
03:37:15,390 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587561039000, eventType=EXT_WRITE_ROWS, serverId=783311, headerLength=19, dataLength=168, nextPosition=852820808, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
03:37:15,390 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
03:37:15,490 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21687371159 -- restarting
03:37:15,581 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21687371159 (sid:6379, cid:7134449)
03:37:15,581 INFO  BinlogConnectorLifecycleListener - Binlog connected.
05:28:49,691 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587561043000, eventType=EXT_UPDATE_ROWS, serverId=813311, headerLength=19, dataLength=2061, nextPosition=856919999, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
05:28:49,692 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
05:28:49,791 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21687376062 -- restarting
05:28:49,881 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21687376062 (sid:6379, cid:7135217)
05:28:49,881 INFO  BinlogConnectorLifecycleListener - Binlog connected.
07:23:06,878 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1587561048000, eventType=EXT_UPDATE_ROWS, serverId=783311, headerLength=19, dataLength=2061, nextPosition=861282127, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:223) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:954) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_232]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_232]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:296) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	... 5 more
07:23:06,879 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
07:23:06,978 WARN  BinlogConnectorReplicator - replicator stopped at position: 805d3a54-5155-ee18-4258-509028341438:1-21687381519 -- restarting
07:23:07,068 INFO  BinaryLogClient - Connected to my_database:3306 at 805d3a54-5155-ee18-4258-509028341438:1-21687381519 (sid:6379, cid:7136004)
07:23:07,068 INFO  BinlogConnectorLifecycleListener - Binlog connected.
```

**Comment by osheroff** [comment]
trying to trace down how we might be leaking `TableMapEventData`.  Maybe once we go into GC thrash hell we get EOF exceptions because the server stops hearing from us.

**Comment by osheroff** [comment]
it seems unlikely we're leaking `TableMapEventData` in maxwell code, but there's definitely an unbounded cache of table map events in mysql-binlog-connector. 

Theory: your server for whatever reason generates an ungodly amount of table_ids ( constantly altering a table or something like that? creating and dropping 5mm tables? ).

Test: let's do `show binlog events in 'binlogfile'` on that server, output that to a file and let's count how many distinct `table_id` values there are. 

BTW, thanks for sticking with it through the debugging session.  As a maintainer it can be frustrating because people often drive by with bugs and then don't stick around to actually help you figure them out, and you're working totally in the dark and you just don't fix the damn things.  So, thanks.

**Comment by acampoh** [comment]
Hello

I have just done a quick math about this. Looking at one random binlog i have seen that on it we have 39126 different table_ids for 2362 tables names there. It seems that this binlog is for around 45 min of activity, so yes, the amount of table_ids is huge :P 

Looking at the description of table_ids it seems, it changes every time it goes in / out from the table cache, even the table is not altered. So it can make sense for me to have this kind of increment of table_ids taking into account this is the biggest db cluster in the company...

We are going to have a look to the settings so maybe we can improve this a bit, but i'm not sure if this will only delay the problem more than fixing it... We are going to bump to 2.5.1 with jmx stats enabled so i hope i can give you more details soon

**Comment by osheroff** [comment]
> Looking at the description of table_ids it seems, it changes every time it goes in / out from the table cache, even the table is not altered. 

Ah, I hadn't been aware of that, I had thought ids only changed on alters.  Good to know.  

> We are going to have a look to the settings so maybe we can improve this a bit, but i'm not sure if this will only delay the problem more than fixing it.

Yeah, it won't fix it for real.  As a band-aid you could just restart maxwell every day or so (or soon enough to prevent the condition).  

Longer term, there's basically a memory leak in one of Maxwell's key libraries (mysql-binlog-connector).  I've just started a fork of it (it seems to have gone unmaintained for a year or so), and as soon as I've solidified the fork I can look into turning the leaking table-map cache into an LRU affair that should fix the problem.

**Comment by osheroff** [comment]
@acompoh when you get a second upgrade to v1.25.3, it should fix the memory leak you're seeing.  I'm gonna close this PR but please do report on how it goes.

thx!
osheroff

**Comment by acampoh** [comment]
I'll prepare a new deploy during next week and let you know how it goes. Thanks for your quick fix!

**Comment by acampoh** [comment]
Hello, just to keep you up to date. Today we have released the new version of maxwell in production. The memory graph looks much much better than before. I'll keep an eye on it during this week and let you know. Thanks!

**Comment by acampoh** [comment]
Hello again. New Update, It seems the issue is still there.... or there was another one related....
Here is how the memory graph looks with version 1.25.3

![image](https://user-images.githubusercontent.com/1070678/81798725-a6e0ff00-9510-11ea-8ec0-ab28b9d9ef48.png)

checking the jmap i see this for that instance

`root@maxwell-8448f5fcd8-xdvt9:/app# jmap -histo:live 59 | head -n20
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:       8187938      288638136  [B (java.base@11.0.7)
   2:       2713133      136586208  [I (java.base@11.0.7)
   3:       5473713      131369112  java.lang.String (java.base@11.0.7)
   4:       2710454      130101792  com.github.shyiko.mysql.binlog.event.TableMapEventData
   5:       2769415       88621280  java.util.HashMap$Node (java.base@11.0.7)
   6:       2749280       65982720  java.lang.Long (java.base@11.0.7)
   7:       2710505       65055040  [J (java.base@11.0.7)
   8:       2710469       65051256  java.util.BitSet (java.base@11.0.7)
   9:          6411       17856112  [Ljava.util.HashMap$Node; (java.base@11.0.7)
  10:         21055        1328272  [Ljava.lang.Object; (java.base@11.0.7)
  11:           586         924792  [C (java.base@11.0.7)
  12:          6668         802208  java.lang.Class (java.base@11.0.7)
  13:         18895         604640  com.zendesk.maxwell.schema.columndef.IntColumnDef
  14:         16193         518176  java.util.concurrent.ConcurrentHashMap$Node (java.base@11.0.7)
  15:          5619         494472  com.zendesk.maxwell.row.RowMapBuffer
  16:         15295         367080  java.util.ArrayList (java.base@11.0.7)
  17:         11613         278712  com.zendesk.maxwell.schema.columndef.StringColumnDef
  18:          4780         229440  java.util.HashMap (java.base@11.0.7)
`
As we increased up to 8 Gb the heap size i'm not sure if this can be normal or something shouldn't be happening....

**Comment by osheroff** [comment]
bah, something went wrong with the release of 1.25.3... no doubt tooling issues related to taking over the mysql-binlog-connector fork, for some reason the LRU cache code never actually made it into that release of maxwell/binlog-connector.

Can you bump against to 1.26.1?  sorry for the trouble.  I double checked that release and the code is definitely in there.

**Comment by osheroff** [comment]
@acampoh you get this fixed?

**Comment by acampoh** [comment]
hello! the service has being deployed tonight in production, so i'll have some info tomorrow. for now it looks ok, but i prefer to keep it working for 24h before getting any conclusion.

**Comment by acampoh** [comment]
Hello. so GOOD news. After 2/3 days working on production in different environments none of the maxwells are using more than 500Mb. What a difference.

I'll close the issue as now this is working so smoothly.
Thanks for the good work!!

**Comment by osheroff** [comment]
glad to hear it adrian.  Thanks for helping make maxwell better for everyone.  how's *that* for a cheery attitude eh?  :)

**Comment by TengHuo** [comment]
Hi @osheroff and @acampoh 

We still got quite high memory usage in some scenario due to memory leak in EventDeserializer (e.g. a lot of tables in one MySQL instance). So I fixed it by cleaning tableMapEventByTableId regularly when got a ROTATE event.

I have submitted a PR here: https://github.com/osheroff/mysql-binlog-connector-java/pull/63

May I ask if you are free to review it? Thanks so much
